export const questionsData = {
    JavaScript: [
        { question: "What is closure in JavaScript?", options: ["A function having access to its own scope only", "A function having access to parent scope", "A function with no access to outer scope", "None of the above"], answer: [1], difficulty: "medium" },
        { question: "Which method converts JSON to JavaScript object?", options: ["JSON.stringify", "JSON.parse", "JSON.toObject", "JSON.convert"], answer: [1], difficulty: "easy" },
        { question: "Which keyword declares a variable that cannot be reassigned?", options: ["var", "let", "const", "static"], answer: [2], difficulty: "easy" },
        { question: "What is the result of '2' + 2 in JavaScript?", options: ["4", "'22'", "NaN", "Error"], answer: [1], difficulty: "medium" },
        { question: "Which array method creates a new array with the results of calling a function on every element?", options: ["map()", "filter()", "reduce()", "forEach()"], answer: [0], difficulty: "medium" },
        { question: "What does the 'this' keyword refer to in a regular function?", options: ["The function itself", "Global object in non-strict mode", "Parent object", "Undefined"], answer: [1], difficulty: "hard" },
        { question: "Which operator is used for strict equality?", options: ["==", "===", "=", "!="], answer: [1], difficulty: "easy" },
        { question: "Which method removes the first element from an array?", options: ["pop()", "shift()", "splice()", "unshift()"], answer: [1], difficulty: "easy" },
        { question: "What is the output of typeof NaN?", options: ["number", "NaN", "undefined", "object"], answer: [0], difficulty: "medium" },
        { question: "Which function is used to call a function immediately with a different context?", options: ["call()", "apply()", "bind()", "invoke()"], answer: [0], difficulty: "hard" },
    ],
    Python: [
        { question: "Which keyword is used to define a function?", options: ["func", "def", "function", "lambda"], answer: [1], difficulty: "easy" },
        { question: "What is the output of print(type([]))?", options: ["list", "dict", "tuple", "array"], answer: [0], difficulty: "easy" },
        { question: "Which method adds an element to a list?", options: ["append()", "add()", "insert()", "push()"], answer: [0], difficulty: "easy" },
        { question: "Which keyword is used for exception handling?", options: ["try", "except", "catch", "finally"], answer: [1], difficulty: "medium" },
        { question: "Which data type is immutable?", options: ["list", "tuple", "dict", "set"], answer: [1], difficulty: "medium" },
        { question: "What does the pass keyword do?", options: ["Exits a loop", "Does nothing", "Raises an error", "Returns None"], answer: [1], difficulty: "medium" },
        { question: "Which operator is used for exponentiation?", options: ["^", "**", "%", "//"], answer: [1], difficulty: "easy" },
        { question: "Which function returns the length of a list?", options: ["size()", "length()", "len()", "count()"], answer: [2], difficulty: "easy" },
        { question: "Which keyword is used to create a class?", options: ["class", "def", "object", "struct"], answer: [0], difficulty: "easy" },
        { question: "Which method removes the last element of a list?", options: ["pop()", "remove()", "del()", "truncate()"], answer: [0], difficulty: "medium" },
    ],
    Java: [
        { question: "Which keyword is used to inherit a class?", options: ["extends", "implements", "inherits", "super"], answer: [0], difficulty: "easy" },
        { question: "Which method is the entry point of a Java program?", options: ["main()", "start()", "init()", "run()"], answer: [0], difficulty: "easy" },
        { question: "Which keyword declares a constant?", options: ["constant", "final", "const", "immutable"], answer: [1], difficulty: "easy" },
        { question: "Which operator is used to compare object references?", options: ["==", "equals()", "===", "!="], answer: [0], difficulty: "medium" },
        { question: "Which package contains Scanner class?", options: ["java.util", "java.io", "java.lang", "java.net"], answer: [0], difficulty: "easy" },
        { question: "Which loop executes at least once?", options: ["for", "while", "do-while", "foreach"], answer: [2], difficulty: "medium" },
        { question: "Which keyword handles exceptions?", options: ["try", "catch", "finally", "All of the above"], answer: [3], difficulty: "medium" },
        { question: "Which access modifier makes a member visible only within the same package?", options: ["private", "public", "protected", "default"], answer: [3], difficulty: "medium" },
        { question: "Which method starts a thread?", options: ["start()", "run()", "execute()", "init()"], answer: [0], difficulty: "medium" },
        { question: "Which method converts a string to integer?", options: ["parseInt()", "Integer.parseInt()", "toInt()", "Number()"], answer: [1], difficulty: "hard" },
    ],
    Cpp: [
        { question: "Which operator is used for scope resolution?", options: ["::", ":", ".", "->"], answer: [0], difficulty: "easy" },
        { question: "Which keyword defines a constant?", options: ["const", "constant", "final", "immutable"], answer: [0], difficulty: "easy" },
        { question: "Which function frees allocated memory?", options: ["delete", "free()", "clear()", "remove()"], answer: [1], difficulty: "medium" },
        { question: "Which is used for inheritance?", options: ["extends", "inherits", ":", "->"], answer: [2], difficulty: "medium" },
        { question: "Which operator accesses pointer members?", options: ["->", ".", "*", "&"], answer: [0], difficulty: "medium" },
        { question: "Which loop runs at least once?", options: ["for", "while", "do-while", "foreach"], answer: [2], difficulty: "medium" },
        { question: "Which header is needed for I/O?", options: ["<stdio.h>", "<iostream>", "<stdlib.h>", "<string.h>"], answer: [1], difficulty: "easy" },
        { question: "Which data type stores true/false?", options: ["int", "bool", "char", "float"], answer: [1], difficulty: "easy" },
        { question: "Which keyword defines virtual functions?", options: ["virtual", "override", "abstract", "interface"], answer: [0], difficulty: "hard" },
        { question: "Which operator is used to dereference a pointer?", options: ["*", "&", "->", "."], answer: [0], difficulty: "medium" },
    ],
    React: [
        { question: "What is JSX?", options: ["A syntax extension for JavaScript", "A library", "A function", "None of the above"], answer: [0], difficulty: "easy" },
        { question: "Which hook is used for state management?", options: ["useEffect", "useState", "useReducer", "useContext"], answer: [1], difficulty: "medium" },
        { question: "Which method renders elements in React DOM?", options: ["ReactDOM.render()", "React.render()", "render()", "ReactDOM.create()"], answer: [0], difficulty: "easy" },
        { question: "How to pass data from parent to child?", options: ["props", "state", "context", "hooks"], answer: [0], difficulty: "easy" },
        { question: "Which hook handles side effects?", options: ["useEffect", "useState", "useMemo", "useRef"], answer: [0], difficulty: "medium" },
        { question: "Which hook gives access to DOM elements?", options: ["useRef", "useState", "useEffect", "useContext"], answer: [0], difficulty: "medium" },
        { question: "What is a key in React?", options: ["Unique identifier for list elements", "A prop", "A hook", "State variable"], answer: [0], difficulty: "easy" },
        { question: "Which hook is used for performance optimization?", options: ["useMemo", "useCallback", "Both", "None"], answer: [2], difficulty: "hard" },
        { question: "Which method updates state?", options: ["setState()", "updateState()", "changeState()", "modifyState()"], answer: [0], difficulty: "easy" },
        { question: "What is the default behavior of React's setState?", options: ["Synchronous", "Asynchronous", "Blocking", "Immediate"], answer: [1], difficulty: "hard" },
    ],
    NodeJS: [
        { question: "Which module is used to create a server?", options: ["http", "fs", "url", "path"], answer: [0], difficulty: "easy" },
        { question: "Which command installs packages?", options: ["npm install", "node install", "npm add", "node add"], answer: [0], difficulty: "easy" },
        { question: "Which object holds command line arguments?", options: ["process", "args", "command", "system"], answer: [0], difficulty: "medium" },
        { question: "Which module handles file operations?", options: ["fs", "path", "url", "os"], answer: [0], difficulty: "easy" },
        { question: "Which method reads a file asynchronously?", options: ["fs.readFile()", "fs.readFileSync()", "fs.open()", "fs.writeFile()"], answer: [0], difficulty: "medium" },
        { question: "Which module gives OS information?", options: ["os", "http", "path", "process"], answer: [0], difficulty: "medium" },
        { question: "Which method writes data to a file?", options: ["fs.writeFile()", "fs.appendFile()", "fs.createWriteStream()", "All of the above"], answer: [3], difficulty: "medium" },
        { question: "Which method creates a buffer?", options: ["Buffer.alloc()", "Buffer.create()", "new Buffer()", "Buffer.new()"], answer: [0], difficulty: "hard" },
        { question: "Which function starts a Node.js server?", options: ["server.listen()", "server.start()", "app.listen()", "app.start()"], answer: [0], difficulty: "medium" },
        { question: "Which module parses URLs?", options: ["url", "querystring", "path", "fs"], answer: [0], difficulty: "medium" },
    ],
    CSharp: [
        { question: "Which method is the entry point?", options: ["Main()", "Start()", "Init()", "Run()"], answer: [0], difficulty: "easy" },
        { question: "Which keyword defines a constant?", options: ["const", "final", "readonly", "immutable"], answer: [0], difficulty: "easy" },
        { question: "Which keyword handles exceptions?", options: ["try", "catch", "finally", "All of the above"], answer: [3], difficulty: "medium" },
        { question: "Which keyword defines inheritance?", options: ["inherits", "extends", ":", "base"], answer: [2], difficulty: "medium" },
        { question: "Which access modifier is default in C#?", options: ["private", "public", "protected", "internal"], answer: [0], difficulty: "medium" },
        { question: "Which method converts string to int?", options: ["Convert.ToInt32()", "int.parse()", "str.toInt()", "All of the above"], answer: [0], difficulty: "easy" },
        { question: "Which keyword is used for interfaces?", options: ["interface", "abstract", "class", "struct"], answer: [0], difficulty: "medium" },
        { question: "Which method overrides base class implementation?", options: ["override", "virtual", "abstract", "new"], answer: [0], difficulty: "medium" },
        { question: "Which loop executes at least once?", options: ["for", "while", "do-while", "foreach"], answer: [2], difficulty: "medium" },
        { question: "Which keyword defines a static member?", options: ["static", "const", "readonly", "global"], answer: [0], difficulty: "easy" },
    ],
    Ruby: [
        { question: "Which keyword defines a method?", options: ["func", "def", "function", "method"], answer: [1], difficulty: "easy" },
        { question: "Which method adds an element to an array?", options: ["push", "append", "add", "insert"], answer: [0], difficulty: "easy" },
        { question: "Which operator concatenates strings?", options: ["+", "&", ".", "concat"], answer: [0], difficulty: "easy" },
        { question: "Which symbol is used for comments?", options: ["#", "//", "/* */", "--"], answer: [0], difficulty: "easy" },
        { question: "Which method removes the last element from an array?", options: ["pop", "delete", "remove", "shift"], answer: [0], difficulty: "medium" },
        { question: "Which keyword defines a class?", options: ["class", "object", "struct", "module"], answer: [0], difficulty: "easy" },
        { question: "Which method iterates over an array?", options: ["each", "map", "for", "loop"], answer: [0], difficulty: "medium" },
        { question: "Which method converts string to integer?", options: ["to_i", "parseInt", "int()", "convert()"], answer: [0], difficulty: "easy" },
        { question: "Which operator checks equality?", options: ["==", "===", "=", "!="], answer: [0], difficulty: "easy" },
        { question: "Which method removes duplicates from an array?", options: ["uniq", "distinct", "unique", "removeDuplicates"], answer: [0], difficulty: "medium" },
    ],
    Go: [
        { question: "Which keyword defines a function?", options: ["func", "def", "function", "method"], answer: [0], difficulty: "easy" },
        { question: "Which operator checks equality?", options: ["==", "=", "===", "!="], answer: [0], difficulty: "easy" },
        { question: "Which keyword declares a variable?", options: ["var", "let", "const", "define"], answer: [0], difficulty: "easy" },
        { question: "Which type is used for floating-point numbers?", options: ["float64", "double", "real", "decimal"], answer: [0], difficulty: "medium" },
        { question: "Which keyword imports packages?", options: ["import", "include", "require", "use"], answer: [0], difficulty: "easy" },
        { question: "Which loop iterates over collections?", options: ["for", "range", "foreach", "while"], answer: [1], difficulty: "medium" },
        { question: "Which type is used for true/false?", options: ["bool", "boolean", "Bit", "Bool"], answer: [0], difficulty: "easy" },
        { question: "Which function prints output to console?", options: ["fmt.Println()", "print()", "console.log()", "echo"], answer: [0], difficulty: "easy" },
        { question: "Which keyword defines a constant?", options: ["const", "final", "immutable", "constant"], answer: [0], difficulty: "medium" },
        { question: "Which function handles errors in Go?", options: ["errors.New()", "throw()", "raise()", "panic()"], answer: [3], difficulty: "hard" },
    ],
};